ark:
  container_name: ark
  image: taxx/ark-server
  environment:
    - SESSIONNAME=Ark Docker
    - SERVERMAP=TheIsland
    - SERVERPASSWORD="" 
    - ADMINPASSWORD=adminpassword
    - BACKUPONSTART=1
    - UPDATEONSTART=1
    - TZ=Europe/Paris
    - GID=1000
    - UID=1000
    - STEAMPORT=7778
    - SERVERPORT=27015
    - RCONPORT=32330   
  volumes:
    - /my/path/to/ark:/ark
  ports:
   - 7778:7778/udp
   - 7778:7778
   - 27015:27015/udp
   - 27015:27015
   - 32330:32330
